server:
  port: 8084
spring:
  application:
    name: auth
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

security:
  jwt:
    secret: "titkos"